### ISSUE TITLE
Can't enter due to no map

### ISSUE THREAD

**Issue by PlzAdoptMee** [qbcore-framework/qb-casino#13]
I joined the qbcore discord to see if the map was in there but it wasn't. How do I get it?

**Comment by BerkieBb** [comment]
There is but it is in a probably unexpected place, https://forum.cfx.re/t/cayo-perico-casino-dlc-ipl-loader/2099391

**Comment by BerkieBb** [comment]
It's in the tutorials section of the discord, the enabling-casino channel

**Comment by PlzAdoptMee** [comment]
I must be in the wrong discord. I dont see a tutorial section in it

**Comment by BerkieBb** [comment]
https://discord.gg/qbcore
This is the discord

**Comment by PlzAdoptMee** [comment]
Interesting Im in that one. All i see is Welcome, Rules, Role-react, giveaway, supporters,  and announcement

**Comment by BerkieBb** [comment]
Go to role-react and get some roles

**Comment by PlzAdoptMee** [comment]
Oh jeez Im dumb. Thank you
